org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Project
version=1.2.0
group=dev.yhdgms1.chainmail_armory
java_version=25

# Common
minecraft_version=26.2
mod_name=Chainmail Armory
mod_author=yhdgms1
mod_id=chainmail_armory
license=MIT
credits=yhdgms1
mod_description=Adds crafting recipe for chainmail armor.
minecraft_version_range=[26.2, 26.3)
neo_form_version=26.2-1

fabric_loader_version=0.19.3
fabric_api_version=0.156.0+26.2

neoforge_version=26.2.0.35-beta
neoforge_loader_version_range=[4,)

# Run options
client_username=Dev
